apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-market-api
  namespace: jobmarket
  labels:
    app: job-market-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: job-market-api
  template:
    metadata:
      name: job-market-api
      labels:
        app: job-market-api
    spec:
      restartPolicy: Always
      containers:
        - name: job-market-api
          envFrom:
            - configMapRef:
                name: job-market-config
            - secretRef:
                name: api-secret
          image: patryka2000/job-api:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080
              protocol: TCP

          startupProbe:
            httpGet: { path: /health/, port: 8080 }
            failureThreshold: 60
            periodSeconds: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet: { path: /health/, port: 8080 }
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet: { path: /health/, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
